[build]
  base = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200